name: Build EXE Launcher

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.3.1

      - name: Restore NuGet packages
        run: nuget restore Launcher.sln

      - name: Build solution
        run: msbuild Launcher.sln /p:Configuration=Release

      - name: Upload EXE
        uses: actions/upload-artifact@v4
        with:
          name: LauncherEXE
          path: Launcher\bin\Release\Launcher.exe
